export const HASHTAGS = [
    '#UBI',
    '#IncomeMarch',
    '#UniversalBasicIncome',
    '#FreedomDividend',
    '#CitizensDividend',
    '#LivableIncome',
    '#GuaranteedLivableIncome',
    '#SocialIncome',
    '#CitizensIncome',
    '#BIG',
    '#BasicIncomeGuarantee',
    '#RentaBásica',
    '#Grundeinkomme',
    '#BGE',
]
